name: HopperSeller
main: ca.coulis.HopperSeller.HopperSeller
version: 1.0
api-version: 1.16
author: coulis
commands:
  hopperseller:
    description: HopperSeller
    usage: /hopperseller
    permission: hopperseller.admin
